<?php
/**
 * Created by PhpStorm.
 * User: tim11
 * Date: 15-11-2018
 * Time: 15:07
 */

class Model extends Crud
{
    private $name;

    public function __construct($table)
    {
        parent::__construct($table);
    }

    public function read($columns, $where_is = array(), $orderBy = "")
    {
        return parent::read($columns, $where_is, $orderBy); // TODO: Change the autogenerated stub
    }

    public function innerJoin($columns, $secondTable, $onColumn, $where_is, $orderBy = "", $limit = "", $offset = "")
    {
        return parent::innerJoin($columns, $secondTable, $onColumn, $where_is, $orderBy, $limit, $offset); // TODO: Change the autogenerated stub
    }
}