<?php
/**
 * Created by PhpStorm.
 * User: tbeek6640
 * Date: 15-11-2018
 * Time: 21:34
 */

class Opleiding extends Model
{
    private $page_title;

    private $description;

    private $ 

    public function __construct()
    {
        parent::__construct();
    }

    public function setDbTable($db_table)
    {
        parent::setDbTable($db_table); // TODO: Change the autogenerated stub
    }

    public function createJsonFile($input)
    {
        parent::createJsonFile($input); // TODO: Change the autogenerated stub
        $this->__destruct();
    }

    public function __destruct()
    {
        parent::__destruct();
    }
}